name: Publish to Packagist

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Publish to Packagist
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: "tahadavari"
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
          package_name: taha-davari/laravel-easy-service-repo
          domain: "packagist.org"
